title: Hervé Beraud | FOSS Hacker at Red Hat / Science Lover
long_title: Hervé Beraud | FOSS Contributor at Red Hat / Science Lover - Personal Website
email: herveberaud.pro@gmail.com
description: >
    Hi, my name is Hervé, I'm a FOSS Contributor at Red Hat and a Python Senior Sofware Engineer at work.
    I'm a python lover, GNU/Linux addict and I'm passionate by computer science! and sciences in general
baseurl: "/"
url: "https://herve.beraud.io"
highlighter: rouge
plugins:
  - jekyll-feed
