title: Hervé Beraud | FOSS Hacker/DevOps Architect
long_title: Hervé Beraud | FOSS Hacker/Devops Architect - Personal Website
email: herveberaud.pro@gmail.com
description: >
    Hi, my name is Hervé, I'm a FOSS Hacker and a DevOps Architect at work.
    I'm a python lover, GNU/Linux addict and I'm passionate by computer science!
baseurl: "/"
url: "http://herve.beraud.ovh"
